### ISSUE TITLE
problems with ceph/s3 configuration of OneProvider

### ISSUE THREAD

**Issue by loomis** [onedata/onedata#5]
Hello.

I've deployed a working OneData infrastructure based on the "getting-started" scenario 3.0.  I'm now trying to modify the configuration files to use ceph and s3 for the storage backend of OneProvider.  Both of these fail with the error:
```
Starting op_panel	[  OK  ]

Failed to start configuration process (code: 400)
For more information please check the logs.
```
Looking through the logs, the OnePanel service started correctly, but there are no other logs with errors/information to indicate what has gone wrong. 

Is it possible to use the OneProvider docker image for something other than a POSIX file system? If so, is there a working example somewhere? If not, how can ceph/s3 support be tested?

The result is the same whether trying S3 or Ceph storage. The configuration file that is used for Ceph is:
```
version: '2.0'

services:
  node1.oneprovider.localhost:
    image: onedata/oneprovider:3.0.0-rc11
    hostname: node1.oneprovider.localhost
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneprovider-1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        # configuration persistence
        - "${ONEPROVIDER_CONFIG_DIR}:/volumes/persistence"
        # data persistence
        - "${ONEPROVIDER_DATA_DIR}:/volumes/storage"
        # Oneprovider
        #- "${OP_PRIV_KEY_PATH}:/volumes/persistence/etc/op_panel/certs/key.pem"
        #- "${OP_CERT_PATH}:/volumes/persistence/etc/op_panel/certs/cert.pem"
        #- "${OP_CACERT_PATH}:/volumes/persistence/etc/op_panel/cacerts/cacert.pem"
        #- "${OP_CACERT_PATH}:/volumes/persistence/etc/op_worker/cacerts/cacert.pem"
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "80:80"
      - "5555:5555"
      - "5556:5556"
      - "6665:6665"
      - "6666:6666"
      - "7443:7443"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
    environment:
      #ONEPANEL_DEBUG_MODE: "true" # prevents container exit on configuration error
      ONEPANEL_BATCH_MODE: "true"
      ONEPROVIDER_CONFIG: |
        cluster:
          domainName: "oneprovider.localhost"
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
          storages:
            nfs1:
              type: "posix"
              mountPoint: "/volumes/storage"
            ceph:
              type: "Ceph"
              username: "client.admin"
              key: "aaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaa=="
              monitorHostname: "185.19.30.30"
              clusterName: "24880865-497f-4aff-80cc-151a7d4fcc60"
              name: "24880865-497f-4aff-80cc-151a7d4fcc60"
        oneprovider:
          register: true
          name: "${PROVIDER_TYPE}_${PROVIDER_FQDN}"
          redirectionPoint: "https://${PROVIDER_FQDN}" # OR IP ADDRESS
          geoLatitude: ${GEO_LATITUDE}
          geoLongitude: ${GEO_LONGITUDE}
        onezone:
          domainName: "${ZONE_FQDN}" # OR IP ADDRESS
        onepanel:
          users:
            admin:
              password: "password"
              userRole: "admin"
```
